apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: http-ingress
  annotations:
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ocelot-gateway
            port:
              number: 80
# Add prefix path for ocelot
---
apiVersion: v1
kind: Service
metadata:
  name: kanvas-np-mailservice-srv
spec:
  type: NodePort
  selector:
    app:  kanvas-mailservice
  ports:
    - name:  kanvas-mailervice
      protocol: TCP
      port: 80
      targetPort: 80