name: Build MailService

on:
  push:
      branches:
      - main
      - fix-mapstructure
env:
  PROJECT_PATH: 'MailService/MailService.csproj'
  TEST_PATH: 'EmailService.Test/MailService.Test.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MAIL_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  
jobs:
 build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release
      
    - name: 'Run tests'
      run: dotnet test ${{ env.TEST_PATH }}

        
    # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 6
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        sonarProjectKey: ahmedjimale1998_mail_service
        sonarProjectName: mail_service
        sonarOrganization: ahmedjimale1998
        dotnetBuildArguments: ./MailService
        dotnetTestArguments: ./EmailService.Test
