name: Build UserService

on:
  push:
    branches: [ fix-mapstructure ]
  pull_request:
    branches: [ fix-mapstructure ]
env:
  PROJECT_PATH: 'UserService/UserService.csproj'
  TEST_PATH: 'UserService.Test/UserService.Test.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  working-directory: ./Kanvas/
  
jobs:
  build:

    runs-on: ubuntu-latest
#     env: 
#       working-directory: ./Kanvas/Kanvas/


    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: | 
        dotnet restore
      working-directory: ${{env.working-directory}}
    - name: Build
      run: |
        dotnet build --no-restore
      working-directory: ${{env.working-directory}}
    - name: Test
      run: | 
        dotnet test --no-build --verbosity normal
        
      working-directory: ${{env.working-directory}}
      
    # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 6
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        sonarProjectKey: ahmedjimale1998_user_service
        sonarProjectName: user_service
        sonarOrganization: ahmedjimale1998
        dotnetBuildArguments: ./UserService
        dotnetTestArguments: ./UserService.Test
