name: Release UserService

on:
  push:
    branches:
      - fix-mapstructure
    paths:
      - "UserService/**"
      - ".github/workflows/release-userservice.yaml"
env:
  PROJECT_PATH: 'UserService/UserService.csproj'
  TEST_PATH: 'UserService.Test/UserService.Test.csproj'
  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USER_SERVICE }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2

    - name: 'Install dotnet'
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'

    - name: 'Restore packages'
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: 'Build project'
      run: dotnet build ${{ env.PROJECT_PATH }} --no-restore --configuration Release

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        file: UserService.Dockerfile
        context: ./
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/kanvas-userservice:latest
        
        # https://github.com/highbyte/sonarscan-dotnet
    - name: SonarScanner for .NET 6
      uses: highbyte/sonarscan-dotnet@v2.1.2
      with:
        sonarProjectKey: ahmedjimale_user_service
        sonarProjectName: user_service
        sonarOrganization: ahmedjimale1998
        dotnetBuildArguments: ./UserService
        dotnetTestArguments: ./UserService.Test

